name: Data Schema Code Convention

on:
  push:
    branches: [LW11]

jobs:
  SQLLinter:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code in Repository
        uses: actions/checkout@v3

      - name: Install SQLFluff
        run: |
          pip install sqlfluff
          pip install sqlfluff-templater-jinja

      - name: Run SQL Linter (PostgreSQL)
        run: |
          sqlfluff lint $GITHUB_WORKSPACE/schema.sql --dialect postgres
