name: Data Schema Code Convention

on:
  workflow_dispatch:

jobs:
  SQLLinter:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code in Repository
        uses: actions/checkout@v3

      - name: Install SQLFluff
        run: |
          python3 -m pip install --upgrade pip
          pip install sqlfluff

      - name: Check files in workflows folder
        run: |
          echo "Listing files in .github/workflows/"
          ls -l .github/workflows/

      - name: Run SQL Linter (PostgreSQL)
        run: |
          sqlfluff fix $GITHUB_WORKSPACE/.github/workflows/schema.sql --dialect postgres
          sqlfluff lint $GITHUB_WORKSPACE/.github/workflows/schema.sql --dialect postgres
