name: Data Schema Code Convention

on:
  workflow_dispatch:

jobs:
  SQLLinter:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code in Repository
        uses: actions/checkout@v3

      - name: Install SQLFluff
        run: |
          python3 -m pip install --upgrade pip
          pip install sqlfluff

      - name: Run SQL Linter (PostgreSQL)
        run: |
          sqlfluff lint .github/workflows/schema.sql --dialect postgres
